# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and test

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_RECIPE_URL: ${{ secrets.REACT_APP_RECIPE_URL }}
      REACT_APP_IMAGE_URL: ${{ secrets.REACT_APP_IMAGE_URL }}
      REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
      REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}
      REACT_APP_TEST: true

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn --frozen-lockfile

      # Run Cypress E2E tests
      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v5
        with:
          build: yarn run build
          start: npx serve -L -s build -l 3000
          wait-on: 'http://localhost:3000'
          browser: chrome

      # Upload Cypress artifacts (screenshots and videos)
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
